# Generated by Django 5.1.3 on 2025-06-28 11:39

import courses.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bloguser_alter_blog_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.BlogMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.ProfilePicturesStorage(), upload_to=''),
        ),
    ]
