# Generated by Django 5.1.3 on 2025-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_image_alter_bloguser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='role',
            field=models.CharField(choices=[('blogger', 'Blogger'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='blogger', help_text="The user's role in the system.", max_length=20),
        ),
    ]
