# Generated by Django 5.1.3 on 2025-07-02 07:54

import courses.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_options_blog_content_blocks_blog_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.BlogMediaStorage(), upload_to=''),
        ),
    ]
