# Generated by Django 5.1.3 on 2025-04-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_video_options_remove_course_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
