# Generated by Django 5.1.3 on 2025-04-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
