# Generated by Django 5.1.3 on 2025-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_assignment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.AlterField(
            model_name='submission',
            name='marks_obtained',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
