# Generated by Django 5.1.3 on 2025-04-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_video_course_alter_submission_marks_obtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
