# Generated by Django 5.1.3 on 2025-04-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_video_video_url'),
        ('user', '0009_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Make_Assignment',
        ),
    ]
