# Generated by Django 5.1.3 on 2025-04-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_modules', to='courses.module'),
        ),
    ]
