# Generated by Django 5.1.3 on 2025-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_module_course_course_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, related_name='module_videos', to='courses.video'),
        ),
    ]
