# Generated by Django 5.1.3 on 2025-04-25 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_learning_outcomes_course_target_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_outcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome1', models.CharField(max_length=100)),
                ('outcome2', models.CharField(max_length=100)),
                ('outcome3', models.CharField(max_length=100)),
                ('outcome4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Required_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('name3', models.CharField(max_length=100)),
                ('name4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Target_audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience1', models.CharField(max_length=100)),
                ('audience2', models.CharField(max_length=100)),
                ('audience3', models.CharField(max_length=100)),
                ('audience4', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='module',
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_learning_outcomes', to='courses.learning_outcomes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_required_materials', to='courses.required_materials'),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_target_audience', to='courses.target_audience'),
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.module', unique=True),
        ),
    ]
