# Generated by Django 5.1.3 on 2025-04-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_learning_outcomes_required_materials_target_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.learning_outcomes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.required_materials'),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.target_audience'),
        ),
        migrations.AlterField(
            model_name='learning_outcomes',
            name='outcome1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='learning_outcomes',
            name='outcome2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='learning_outcomes',
            name='outcome3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='learning_outcomes',
            name='outcome4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='required_materials',
            name='name1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='required_materials',
            name='name2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='required_materials',
            name='name3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='required_materials',
            name='name4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='target_audience',
            name='audience1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='target_audience',
            name='audience2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='target_audience',
            name='audience3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='target_audience',
            name='audience4',
            field=models.CharField(max_length=200),
        ),
    ]
