# Generated by Django 5.1.3 on 2025-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_learning_outcomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_audience',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
