# Generated by Django 5.1.3 on 2025-04-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_target_audience_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_note',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('note_file', models.FileField(upload_to='course_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='preview_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='module',
            name='video',
        ),
        migrations.AddField(
            model_name='module',
            name='course_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_notes', to='courses.course_note', unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_videos', to='courses.video', unique=True),
        ),
    ]
