# Generated by Django 5.1.3 on 2025-04-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_note_course_preview_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_note',
            new_name='CourseNote',
        ),
        migrations.RenameModel(
            old_name='Learning_outcomes',
            new_name='LearningOutcome',
        ),
        migrations.RenameModel(
            old_name='Required_materials',
            new_name='RequiredMaterial',
        ),
        migrations.RenameModel(
            old_name='Target_audience',
            new_name='TargetAudience',
        ),
    ]
