# Generated by Django 5.1.3 on 2025-04-27 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_rename_course_note_coursenote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module',
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='courses.module')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum'),
        ),
    ]
