# Generated by Django 5.1.3 on 2025-04-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_module_curriculum_course_curriculum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Curriculum',
            new_name='curriculum',
        ),
    ]
