# Generated by Django 5.1.3 on 2025-04-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_rename_curriculum_course_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursenote', unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.video', unique=True),
        ),
    ]
