# Generated by Django 5.1.3 on 2025-04-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_curriculum_module_alter_module_course_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='module',
        ),
        migrations.RemoveField(
            model_name='module',
            name='video',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, to='courses.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='courses.video'),
        ),
    ]
