# Generated by Django 5.1.3 on 2025-04-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_curriculum_module_remove_module_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preview_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='preview_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
