# Generated by Django 5.1.3 on 2025-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_course_preview_url_remove_video_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='outcome4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requiredmaterial',
            name='name4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='audience4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
