# Generated by Django 5.1.3 on 2025-05-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_learningoutcome_outcome4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
