# Generated by Django 5.1.3 on 2025-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_courselibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='courseorderitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='CourseOrder',
        ),
        migrations.DeleteModel(
            name='CourseOrderItem',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
