# Generated by Django 5.1.3 on 2025-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_courseorderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLibraryVideo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='course_library/')),
                ('video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='courselibrary',
            name='courselibraryvideo',
            field=models.ManyToManyField(blank=True, null=True, to='courses.courselibraryvideo'),
        ),
    ]
