# Generated by Django 5.1.3 on 2025-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_courselibraryvideo_courselibrary_courselibraryvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselibraryvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_library/'),
        ),
    ]
