# Generated by Django 5.1.3 on 2025-05-16 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_courseenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselibrary',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='courselibrary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courselibrary'),
        ),
    ]
