# Generated by Django 5.1.3 on 2025-05-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_remove_courselibrary_course_course_courselibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courselibrary',
        ),
        migrations.AddField(
            model_name='courselibrary',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_library', to='courses.course'),
        ),
    ]
