# Generated by Django 5.1.3 on 2025-05-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_remove_course_courselibrary_courselibrary_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselibrary',
            name='course',
        ),
    ]
