# Generated by Django 5.1.3 on 2025-05-16 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_remove_courselibrary_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courselibrary'),
        ),
    ]
