# Generated by Django 5.1.3 on 2025-05-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_course_course_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.CharField(help_text='The name of the person receiving the certificate.', max_length=255, verbose_name='Participant Name')),
                ('course_name', models.CharField(help_text='The name of the completed course.', max_length=255, verbose_name='Course Name')),
                ('completion_date', models.DateField(help_text='The date the course was completed.', verbose_name='Completion Date')),
                ('signature', models.CharField(blank=True, help_text='The name or file path of the signature.', max_length=255, null=True, verbose_name='Signature')),
            ],
            options={
                'verbose_name': 'Completion Certificate',
                'verbose_name_plural': 'Completion Certificates',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_library',
        ),
        migrations.AddField(
            model_name='courselibrary',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
