# Generated by Django 5.1.3 on 2025-05-28 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_completioncertificate_remove_course_course_library_and_more'),
        ('user', '0017_alter_customuser_options_customuser_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_courses', to='user.teacherprofile'),
        ),
    ]
