# Generated by Django 5.1.3 on 2025-05-28 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_alter_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
