# Generated by Django 5.1.3 on 2025-06-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_course_instructor'),
        ('user', '0019_alter_teacherprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum'),
        ),
        migrations.AlterField(
            model_name='course',
            name='estimated_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_description',
            field=models.CharField(max_length=255, default='No description provided'), # <-- ADD DEFAULT HERE
            preserve_default=False, # <-- IMPORTANT: Tells Django to remove this default after migration
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.requiredmaterial', default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.targetaudience', default=1),
        ),
        migrations.AlterField(
            model_name='courselibrary',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courselibrary',
            name='courselibraryvideo',
            field=models.ManyToManyField(to='courses.courselibraryvideo'),
        ),
        migrations.AlterField(
            model_name='courselibrary',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='courselibraryvideo',
            name='video_file',
            field=models.FileField(upload_to='course_library/'),
        ),
        migrations.AlterField(
            model_name='courselibraryvideo',
            name='video_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='module',
            field=models.ManyToManyField(to='courses.module'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='outcome4',
            field=models.CharField(max_length=200, default='No specific outcome'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='make_assignment',
            name='file',
            field=models.FileField(upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='make_assignment',
            name='total_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='course_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursenote', default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.ManyToManyField(to='courses.video'),
        ),
        migrations.AlterField(
            model_name='requiredmaterial',
            name='name4',
            field=models.CharField(max_length=200, default='No specific required-material'),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='audience4',
            field=models.CharField(max_length=200, default='No specific target audience'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(help_text="Duration of the video (e.g., '15 minutes', '30:45')", max_length=50, default='0:00'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=60, default=''),
        ),
    ]
