# Generated by Django 5.1.3 on 2025-06-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_alter_course_curriculum_alter_course_estimated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
