# Generated by Django 5.1.3 on 2025-06-27 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_alter_course_preview_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='required_materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.requiredmaterial'),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.targetaudience'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='outcome4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='course_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursenote'),
        ),
        migrations.AlterField(
            model_name='requiredmaterial',
            name='name4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='audience4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(help_text="Duration of the video (e.g., '15 minutes', '30:45')", max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=60),
        ),
    ]
