# Generated by Django 5.1.3 on 2025-06-28 06:17

import courses.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_alter_course_required_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_assignment',
            name='file',
        ),
        migrations.AddField(
            model_name='make_assignment',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.AssignmentStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.CourseMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='courselibraryvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.VideoMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='courselibraryvideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coursenote',
            name='note_file',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.CourseNotesStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.VideoMediaStorage(), upload_to=''),
        ),
    ]
