# Generated by Django 5.1.3 on 2025-06-28 06:29

import courses.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_remove_make_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_id',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.VideoMediaStorage(), upload_to=''),
        ),
    ]
