# Generated by Django 5.1.3 on 2025-06-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_alter_course_preview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
