# Generated by Django 5.1.3 on 2025-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_video_description_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.FloatField(default=1500),
        ),
    ]
