# Generated by Django 5.1.3 on 2025-07-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_course_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, to='courses.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursenote'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='courses.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
