# Generated by Django 5.1.3 on 2025-07-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_alter_curriculum_module_alter_module_course_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.TextField()),
                ('include2', models.TextField()),
                ('include3', models.TextField()),
                ('include4', models.TextField()),
                ('include5', models.TextField()),
                ('include6', models.TextField()),
                ('include7', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_include',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course_include'),
        ),
    ]
