# Generated by Django 5.1.3 on 2025-07-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_course_include_course_course_include'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make_assignment',
            old_name='video_file',
            new_name='file',
        ),
    ]
