# Generated by Django 5.1.3 on 2025-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_rename_video_file_make_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_materials',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_audience',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='LearningOutcome',
        ),
        migrations.DeleteModel(
            name='RequiredMaterial',
        ),
        migrations.DeleteModel(
            name='TargetAudience',
        ),
    ]
