# Generated by Django 5.1.3 on 2025-08-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_alter_course_learning_outcomes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='event_icons/')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('event_excerpt', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='EST', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('instructor', models.CharField(max_length=100)),
                ('instructor_info', models.TextField()),
                ('workshop', models.JSONField(blank=True, default=dict, null=True)),
                ('who_can_attend', models.TextField(blank=True, help_text="Comma-separated list of attendees' emails", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
