# Generated by Django 5.1.3 on 2025-08-15 13:40

import courses.storages_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(storage=courses.storages_backends.EventStorage, upload_to=''),
        ),
    ]
