# Generated by Django 5.1.3 on 2025-09-13 15:49

import courses.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginners friendly', 'Beginners Friendly'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courselibrary',
            name='file',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.CourseLibraryStorage(), upload_to=''),
        ),
    ]
