# Generated by Django 5.1.3 on 2025-10-20 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculum'),
        ),
        migrations.AlterField(
            model_name='course',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
