# Generated by Django 5.1.3 on 2025-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_teacherprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('Assign_teaching_position', 'Can assign teaching position'), ('create_course_videos', 'can create course videos'), ('create_course_notes', 'can create course notes'), ('edit_course_notes', 'can create course notes'), ('view_payments', 'can view payments'), ('make_payments', 'can make payments'), ('make_assignments', 'can make assignments'), ('view_assignments', 'can view assignments'), ('add_students_to_course', 'can add students to course'), ('view_students_in_course', 'can view all students in course'), ('edit_students_in_course', 'can edit all students in course'), ('view_student_progress', 'view students progress'), ('view_attendance_records', 'view attendance'), ('send_assignments', 'can send assignments'), ('view_course', 'can view all course')]},
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='course_taken',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='past_experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
