# Generated by Django 5.1.3 on 2025-05-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_customuser_course_notification_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(db_column='_id', editable=False, max_length=24, primary_key=True, serialize=False, unique=True),
        ),
    ]
