# Generated by Django 5.1.3 on 2025-06-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_teacherprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
