# Generated by Django 5.1.3 on 2025-06-27 20:43

import courses.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_teacherprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
