# Generated by Django 5.1.3 on 2025-06-28 06:17

import courses.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.ProfilePicturesStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.SubmissionStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, storage=courses.storages_backends.TeacherPicturesStorage(), upload_to=''),
        ),
    ]
