# Generated by Django 5.1.3 on 2025-07-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default='SIGNUP', max_length=20),
        ),
    ]
