
name: Deployment
run-name: "Deployment started by @${{github.actor}}"
on:
  workflow_dispatch:
  #push:
  #  branches: [main]
    
jobs:      
  test:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
